export const safeAbi = [
    {
        type: "function",
        name: "setup",
        stateMutability: "nonpayable",
        inputs: [
            { name: "_owners", type: "address[]" },
            { name: "_threshold", type: "uint256" },
            { name: "to", type: "address" },
            { name: "data", type: "bytes" },
            { name: "fallbackHandler", type: "address" },
            { name: "paymentToken", type: "address" },
            { name: "payment", type: "uint256" },
            { name: "paymentReceiver", type: "address" },
        ],
        outputs: [],
    },
    {
        type: "function",
        name: "getOwners",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "address[]" }],
    },
    {
        type: "function",
        name: "getThreshold",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "nonce",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "uint256" }],
    },
    {
        type: "function",
        name: "getTransactionHash",
        stateMutability: "view",
        inputs: [
            { name: "to", type: "address" },
            { name: "value", type: "uint256" },
            { name: "data", type: "bytes" },
            { name: "operation", type: "uint8" },
            { name: "safeTxGas", type: "uint256" },
            { name: "baseGas", type: "uint256" },
            { name: "gasPrice", type: "uint256" },
            { name: "gasToken", type: "address" },
            { name: "refundReceiver", type: "address" },
            { name: "_nonce", type: "uint256" },
        ],
        outputs: [{ type: "bytes32" }],
    },
    {
        type: "function",
        name: "execTransaction",
        stateMutability: "payable",
        inputs: [
            { name: "to", type: "address" },
            { name: "value", type: "uint256" },
            { name: "data", type: "bytes" },
            { name: "operation", type: "uint8" },
            { name: "safeTxGas", type: "uint256" },
            { name: "baseGas", type: "uint256" },
            { name: "gasPrice", type: "uint256" },
            { name: "gasToken", type: "address" },
            { name: "refundReceiver", type: "address" },
            { name: "signatures", type: "bytes" },
        ],
        outputs: [{ type: "bool" }],
    },
    {
        type: "function",
        name: "domainSeparator",
        stateMutability: "view",
        inputs: [],
        outputs: [{ type: "bytes32" }],
    },
];
export const safeProxyFactoryAbi = [
    {
        type: "function",
        name: "createProxyWithNonce",
        stateMutability: "nonpayable",
        inputs: [
            { name: "_singleton", type: "address" },
            { name: "initializer", type: "bytes" },
            { name: "saltNonce", type: "uint256" },
        ],
        outputs: [{ name: "proxy", type: "address" }],
    },
    {
        type: "event",
        name: "ProxyCreation",
        inputs: [
            { name: "proxy", type: "address", indexed: false },
            { name: "singleton", type: "address", indexed: false },
        ],
    },
];
